#! /usr/bin/env bash
BIN_DIRS="${HOME}/bin ${HOME}/local/bin"

for bindir in $BIN_DIRS ; do
  if [ -d "$bindir" ]; then
   echo $bindir
   PATH="$bindir":$PATH
   echo Path now $PATH
  fi
done
export PATH

